import './globals.css'
 
export const metadata = {
  title: 'Matías García',
  description: 'Generated by create next app',
}
 
export default function RootLayout({ children }) {
  return (
    <html className='scroll-smooth' lang="en">
      <body className='animate-gradient-right'>{children}</body>
    </html>
  )
}